### ISSUE TITLE
Accessor for communication processes

### ISSUE THREAD

**Issue by martinmcclure** [GemTalk/RemoteServiceReplication#120]
To know which processes one should not attempt to debug through an RSR-based debugger, this message would be useful:

RsrConnection >> communicationProcesses

It should answer a collection of processes (if any) that are specific to that connection and crucial to its operation. The number and nature of the processes varies depending on what kind of channel the connection uses.

**Comment by kurtkilpela** [comment]
Implemented in f718ce06c619e6924e9cac71e674b99843452f9d

Send #vitalProcesses to an instance of RsrConnection to get the processes which should not be debugged.
