### ISSUE TITLE
Listen on specific port range

### ISSUE THREAD

**Issue by martinmcclure** [GemTalk/RemoteServiceReplication#136]
This is a customer request. 

For the Sparkle-Gci use case, and to be firewall-friendly, we need API in RSR to listen on an open port within a specified limited range, then return the port number actually being listened on.

At the low level, I think we can only specify one port at a time to listen on, and the listen will fail if there is already a process listening on that port. One strategy that seems like it might work well is to initially choose a random port within the range, then increment from there, wrapping around from the top of the range to the bottom. 

A simpler strategy that would work well for very small port ranges would be to try the lowest port and increment to the highest port.

**Comment by kurtkilpela** [comment]
Martin's work has been merged into main-v2 at commit d468a15934ea63e043256cc95045d05b966340de. Buffered socket streams were added afterwards on martin-136PortRange branch. This is implemented in main-v2 already, in a different manner.

Merge commit is d468a15934ea63e043256cc95045d05b966340de
