### ISSUE TITLE
RSR doesn't support Unicode16

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/RemoteServiceReplication#138]
Unicode16 classes aren't supported currently by RSR. 

The theory is that `RsrReference class>>initializeReferenceMapping` could just have this code added and it will just work. That theory is untested.
```
referenceMapping
        at: Unicode16
        put: RsrStringReference.
```

**Comment by kurtkilpela** [comment]
Fixed by 25b4bab828691fc39b72a7aec484e051be0b2bdf

**Comment by ericwinger** [comment]
I don't think this fix is working. Evaluating this expression in topaz gives me a Unicode16 string but using JfP with RSR it just kind of dies in the _executeInContext: and I can't see what's happening beyond that because something is going wrong in RSR (I think). 
```
topaz 1> run
| tempMethod | 
tempMethod :='''aa'', (String with: (Character withValue: 353)), ''bb'''    _compileInContext: nil symbolList: Rowan image symbolList.
tempMethod _executeInContext: nil.
%
[160091905 size:5  Unicode16] aa\u0161bb
```

The way JfP compiles the method can be found in this method: 
```
RowanAnsweringService>>basicExec:context:shouldDebug:returningString:
basicExec: aString context: oop shouldDebug: shouldDebug returningString: returnStringBoolean
	| object symbolList tempMethod result return  |
	object := Object _objectForOop: oop.
	symbolList := Rowan image symbolList.
	[ tempMethod := aString _compileInContext: object symbolList: symbolList ]
		on: CompileError
		do: [ :ex | 
			answer := Array with: false with: ex errorDetails with: aString.
			^ answer ].
	shouldDebug
		ifTrue: [ 
			| theResult |
			theResult := tempMethod setBreakAtStepPoint: 1 breakpointLevel: 1. 
			RowanDebuggerService new saveProcessOop: GsProcess _current asOop ].
	[ 
	result := tempMethod _executeInContext: object.
	return := returnStringBoolean
		ifTrue: [ result printString ]
		ifFalse: [ result ].
	answer := Array with: true with: result asOop with: return ]
		ensure: [ 
			shouldDebug
				ifTrue: [ tempMethod clearBreakAtStepPoint: 1 ] ].
	RowanService autoCommit == true
		ifTrue: [ System commitTransaction ].
	^ answer
```

**Comment by ericwinger** [comment]
Looks like I had the wrong shaw loaded. One (who reads comments in issues carefully) should load the sha in this comment. https://github.com/GemTalk/RemoteServiceReplication/issues/138#issuecomment-2445031327
https://github.com/GemTalk/RemoteServiceReplication/commit/25b4bab828691fc39b72a7aec484e051be0b2bdf
