### ISSUE TITLE
More information to debug "Incorrectly encoded instance detected"

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/RemoteServiceReplication#139]
When RSR finds a problem with instances having an incorrect encoding, no stack is provided and the only message you get is:
```
Incorrectly encoded instance detected
```
This provides little help when replicating a complex object. It seems that RSR should be able to return the class of the instance and the name of the problematic inst var (or at least the index).

**Comment by kurtkilpela** [comment]
Fixed in f7f10e730dc23f604407f8a3fb1bb340c4f0f0a3 and 56719073c387c52bde71953050f3638759fc4765.

The message will now be similar to `Expected 0 value(s) for template RsrServiceNoInstVars but received 1 value(s) instead. Verify peers have compatible template definitions.`.
