### ISSUE TITLE
More specific error message when ensuring registration

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/RemoteServiceReplication#140]
If RsrConnection >> _ensureRegistered: finds that a service is already registered to a different connect, it throws an error. However, the error class signaled is RsrAlreadyRegistered which is a bit ambiguous as to which connection the service is already registered. A more clear signal "RsrAlreadyRegisteredToDifferentConnection" would be helpful.

**Comment by kurtkilpela** [comment]
RsrAlreadyRegistered renamed to RsrAlreadyRegisteredWithAnotherConnection in dbacb56af359d5076f7da85d947bfed9a122814e
