### ISSUE TITLE
Reading socket process doesn't get closed on disconnect

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/RemoteServiceReplication#144]
Using GCI connections on RSR in Pharo, when doing a disconnect, the reading thread doesn't go away. I've been struggling with using RSR in Pharo tests and I think this is causing problems with tests randomly hanging although I can't prove it. 

Before connection: (no RSR processes) 
![image](https://github.com/GemTalk/RemoteServiceReplication/assets/36212516/ba89e4cc-0b4c-40e6-8e49-4f3e2690080f)

After connection:  (reader/writer processes both present)
![image](https://github.com/GemTalk/RemoteServiceReplication/assets/36212516/babede7a-bb32-4209-9a7b-64e5298003c0)

After disconnect: (reader thread still around) 
![image](https://github.com/GemTalk/RemoteServiceReplication/assets/36212516/e4a9d5d1-3358-48bd-9460-220c44b509f6)

**Comment by kurtkilpela** [comment]
Appears to be resolved by 2115ab8e6fccd545c58b7d70a567919cd23a6a17
