### ISSUE TITLE
use #cull: instead of #value: when using #when:catch: 

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/RemoteServiceReplication#145]
`RsrPromise>>when:catch:` gets sent #value: when the promise is fulfilled. However, it might be nicer if #cull: is sent to avoid the necessity of having a block argument. 

FWIW, it's hard to debug an improperly formed block if error messages are getting suppressed as was my situation.

**Comment by kurtkilpela** [comment]
Fixed in f84398f10f4bebe213450ee80ef35c1813287903
