### ISSUE TITLE
RSR should notify (always) if service has mismatched inst vars

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/RemoteServiceReplication#146]
In this case, I had a client service defined,
```
RowanAutoCommitService {autoCommit postUpdateBlock}
    RowanAutoCommitServiceClient {inCommand}
```
But the server service superclass wasn't identical
```
RowanAutoCommitService {autoCommit }
    RowanAutoCommitServiceServer {}
```

The incorrect inst vars is a bug in my code but finding it was difficult. 

RSR didn't throw an error or anything that I could find. Services were sent to RSR but not received, as logging showed. Other services with properly defined inst vars were received just fine. I only chanced upon the problem. Pushing down postUpdateBlock to the client subclass fixed the problem. 

Although I think it is supposed already, RSR should notify you if you have mismatched inst vars.

**Comment by kurtkilpela** [comment]
See #139.
