### ISSUE TITLE
Unexpected EOF from SSL during write output error

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/RemoteServiceReplication#149]
Not sure if this is related to RSR as the error appears to come from the GCI, but adding issue here for review by those more knowledgeable than me. Adding stack and screen shot. 

I had gotten an error from RSR saying the connection was lost on a windows pharo (rebus). Then pressed disconnect on the Jadeite for Pharo connection launcher resulting in this walkback. 

![image](https://github.com/GemTalk/RemoteServiceReplication/assets/36212516/65ee5b95-334b-45cc-b8fc-2394f93821cb)

[20240620_RSR_walkback.txt](https://github.com/user-attachments/files/15918557/20240620_RSR_walkback.txt)

**Comment by kurtkilpela** [comment]
This was lost by the sudden loss of a gem and is unrelated to RSR.
