### ISSUE TITLE
RsrConnection thinks connection is open even though it's socket reading and writing threads are gone

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/RemoteServiceReplication#150]
I'm not yet sure what's stopping the RSR socket reader and writer pharo processes, but they are going away and RsrConnection>>isOpen returns true. That causes any RSR message to hang. 

![image](https://github.com/user-attachments/assets/ac2a8d6b-e844-4378-8685-0054e7a85e33)

**Comment by kurtkilpela** [comment]
Closing in favor of #143
