### ISSUE TITLE
Running RsrGarbageCollector class>>maximumReclamation dirties method

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/RemoteServiceReplication#151]
Running `RsrGarbageCollector maximumReclamation `  dirties the RSR package in Pharo. Attaching screen recording. 

This is a handy method for getting rid of Pharo garbage so it would be nice if it didn't dirty the RSR package. 

https://github.com/user-attachments/assets/f667f4e5-63b5-480d-a0c1-1b764ac6c2d1

**Comment by kurtkilpela** [comment]
Fixed by 0d78712304938e62f112db5b4bbc44447bccd3d9
