### ISSUE TITLE
Can't run as a less-privileged user

### ISSUE THREAD

**Issue by martinmcclure** [GemTalk/RemoteServiceReplication#91]
Now that the RSR classes are put in Globals, they must be installed as SystemUser. However, it would be good to be able to run RSR in gems that are logged in as other, less-privileged, users. Attempts to do this are getting this error:

===============================================================
Starting to listen
===============================================================
ERROR 2116 , a SecurityError occurred (error 2116), An attempt was made to modify the object RsrProcessModel in objectSecurityPolicyId 1 with insufficient authorization.
Stopping at line 13 of /home/martin/Repositories/RemoteServiceReplication/scripts/runServer.topaz
topaz 1> where
==> 1 SecurityError (AbstractException) >> _signalFromPrimitive: @5 line 15
2 RsrProcessModel class >> resetCurrent         @1 line 1
3 RsrProcessModel class >> current              @3 line 3
4 RsrProcessModel class >> fork:                @2 line 3
5 RsrDispatchQueue >> start                     @3 line 5
6 RsrConnection >> open                         @2 line 3
7 RsrAcceptConnection >> waitForConnection      @12 line 21
8 Executed Code                                 @7 line 6
9 GsNMethod class >> _gsReturnToC               @1 line 11

**Comment by martinmcclure** [comment]
3 commits merged to development that fix this by using SessionTemps. Dolphin probably needs updating, so leaving open until Kurt can get to that.

**Comment by kurtkilpela** [comment]
Dolphin has been updated in 2ac22cc6df1471bfae67ad05ace8935c0b162539. Tests now pass in Dolphin again.
