### ISSUE TITLE
Need API to reserve a wildcard port for listening, then actually accept as a separate step

### ISSUE THREAD

**Issue by martinmcclure** [GemTalk/RemoteServiceReplication#94]
The GCI way for Sparkle to connect to GemStone will be:
1) Launch a gem using GCI.
2) Make a GCI call that requests a "pre-start" of RSR. The reply to this includes a wildcard port number and a random token used for authentication.
3) The client then makes a GCI call that tells RSR to accept a connection, then does not return to the GCI client until that connection is closed.
4) The client makes an RSR connection to the port number returned earlier via GCI, and authenticates using the random token returned earlier via GCI.

So binding the socket to the wildcard port to get a known-available port number must be able to be a separate step from actually accepting a connection.

**Comment by kurtkilpela** [comment]
Implemented the internals of a token exchange process. In this listed commit, the token is hardcoded to 128-bit 0 value.

See 717697733ede2fb9fccab46094196de93f28c507

**Comment by kurtkilpela** [comment]
RsrAcceptConnection now can now bind and listen on a port and then later accept a Connection on the specified port. I'll see about integrating the GCI library and implementing startup of a gem via GCI.

See 2ac22cc6df1471bfae67ad05ace8935c0b162539

**Comment by martinmcclure** [comment]
See [Sparkle #68](https://github.com/GemTalk/Sparkle/issues/68) which depends on this issue.
Not _essential_, but this would be nice to get fixed before the next demo, which could be in a week or so.

**Comment by kurtkilpela** [comment]
Added #listeningPort to RsrAcceptConnection which allows the use of wildcard ports. Added test to ensure this works in GemStone, Pharo, and Dolphin. Created an RsrAcceptConnection by providing a port of 0 activated the functionality.

See d2cf638271decb1edb56de954fa95fc735e04d92

**Comment by kurtkilpela** [comment]
Generating a proper token is still required before this ticket is closed.

**Comment by kurtkilpela** [comment]
A random token is now generated.

See 6e6355851d2043c1e2fb0d72871ad7b37f618cb6
