### ISSUE TITLE
Buffer Read/Writes to Stream

### ISSUE THREAD

**Issue by kurtkilpela** [GemTalk/RemoteServiceReplication#97]
RSR currently uses a streaming interface to read and write data to the socket. This data is not buffered in any way. Each read or write request is an independent system call. This is problematic as it means that for most objects, there is a sequence of write commands which write 8 bytes on each call.

Instead, RSR should buffer these reads and writes. The #flush message is already sent once no additional data is available to write to the wire.

**Comment by rjsargent** [comment]
[At the risk of being Captain Obvious] ...
You probably should send intermediate flushes if the data is large enough.
e.g.
generate large response --- transmit large response --- process large response
yields a long delay before everything is done. Overlapping smaller chunks of generate/transmit/process will reduce the overall time needed for large enough messages.

I have no idea whether 16K, 64K, 256K, 1M, 16M or what makes for the best performance.

**Comment by kurtkilpela** [comment]
If data is beyond the size of the buffer, I suspect it will be written directly w/o buffering.

**Comment by kurtkilpela** [comment]
Refactored RsrStream hierarchy to remove previous experiments and to make SocketStream a subclass of (Rsr)Stream.

See 99d2ac732f115efb1f82c0bf52627860d88aeca7

**Comment by kurtkilpela** [comment]
As of 41c9495191c44d9fdf176e929eb411ec8efcf688, writes are now buffered.

This does not use the implementation from martin-bufferedSockets. Instead, it uses the strategy of wrapping the SocketStream with an RsrBufferedStream. Past conversations with Martin suggest he would prefer this method.
