### ISSUE TITLE
Lazy initialization of protected variable causes failure for less-privileged users

### ISSUE THREAD

**Issue by martinmcclure** [GemTalk/RemoteServiceReplication#98]
Related to #91 and https://github.com/GemTalk/Sparkle/issues/46 -- it looks like there might be lazy initialization that cannot be run by less-privileged users.

Stack excerpt:

28 SecurityError (AbstractException) >> _signalFromPrimitive: @1 line 8
29 RsrReference class >> initializeReferenceMapping @1 line 1
30 RsrReference class >> referenceMapping        @3 line 3
31 RsrReference class >> referenceClassFor:      @5 line 5
32 RsrSnapshotAnalysis >> referenceClassFor:     @2 line 3
33 RsrSnapshotAnalysis >> analyze:               @6 line 5

**Comment by martinmcclure** [comment]
This was a bit of a tangle, but has been fixed for GemStone and Pharo with commits over the past several hours. Assigning to Kurt and leaving open for whatever Dolphin work is needed.

**Comment by kurtkilpela** [comment]
No additional work is required for Dolphin w/ the current version of development.
