### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by martinmcclure** [GemTalk/RemoteServiceReplication#99]
Reported by a customer -- when loading the bootstrap, there are three compiler warnings.

RsrServiceSnapshot >> decode: aStream using: aDecoder
WARNING: unused method temp 'templateClass'

RsrSnapshotAnalysisTest >> testNewServicesInDictionary
WARNING: unused method temp 'expected'

RsrSnapshotAnalysisTest >> testServiceReferencingAnotherService
WARNING: unused method temp 'expected'

**Comment by martinmcclure** [comment]
Fixed with commit 0817bfc1

**Comment by dalehenrich** [comment]
I've got code in the Rowan load script that fails/reports compiler warnings during load ... sound like it's time to add this to the Sparkle/RSR scripts

**Comment by dalehenrich** [comment]
I've added the compile warning check to the installation script ... in Rowan, I've found that the best place to put the compile warning check is in the batch job used to run tests ... I run Rowan tests in a fresh extent0.rowan.dbf and if compile warnings show up the test is failed ... I always run tests BEFORE merging code into the release branches ... it is always prudent to run tests before merging code into a branch that users will be using ...

**Comment by martinmcclure** [comment]
Installing with this change to the script creates a zero-length topazerrors.log file. Is this expected? If so, should that go in a .gitignore so it doesn't get committed?

**Comment by dalehenrich** [comment]
that's the resultcheck in action ... while the topazerrors.log file is not unexpected, where the file is dropped depends upon where the script gets run, I usually run topaz in a directory outside of the repository itself .... if there is a standard directory that the script is run from then a .gitignore wouldn't hurt ... which directory is the standard location?
